fixtures:
  forge_modules:
    apt: puppetlabs/apt
    elastic_stack: elastic/elastic_stack
    stdlib: puppetlabs/stdlib
    zypprepo: darin/zypprepo
    yumrepo: puppetlabs/yumrepo_core

symlinks:
    logstash: #{source_dir}
